### PR TITLE
Check pr items

### LINKED ISSUE #3: TypeError: Cannot call method 'filter' of undefined
Here the result of the start command:

```
➜  repository-downloader (master) ✔ ./start
info  Getting the organizations you belong to.
info  Getting all your repositories.
   >  Page: 1
   >  Page: 2
   >  Page: 3
   >  Page: 4
   >  Page: 5
   >  Page: 6
   >  Page: 7
   >  Page: 8
   >  Page: 9
info  Getting the repositories where pborreli created pull requests.
   >  Page: 1
   >  Page: 2
   >  Page: 3
   >  Page: 4
   >  Page: 5
   >  Page: 6
   >  Page: 7
   >  Page: 8
   >  Page: 9
   >  Page: 10
   >  Page: 11

TypeError: Cannot call method 'filter' of undefined
    at /Users/pborreli/Contrib/repository-downloader/github.js:84:50
    at Request._callback (/Users/pborreli/Contrib/repository-downloader/github.js:43:9)
    at Request.self.callback (/Users/pborreli/Contrib/repository-downloader/node_modules/request/request.js:344:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/pborreli/Contrib/repository-downloader/node_modules/request/request.js:1239:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/pborreli/Contrib/repository-downloader/node_modules/request/request.js:1187:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
info  Getting the organizations you belong to.
error SyntaxError: Unexpected end of input
>> */
./import.sh: line 4: cd: */: No such file or directory
>> */
./import.sh: line 7: cd: */: No such file or directory
./import.sh: line 9: cd: */: No such file or directory
>> */
error This is not a git project.

### LINKED ISSUE #4: Error: spawn EAGAIN
Running the start command: 

```
info  Downloading all your repositories.
   >  Repository: pborreli/18f.gsa.gov
   >  Repository: pborreli/24pullrequests
   >  Repository: pborreli/42-protips-2014-conf
   >  Repository: pborreli/AB
   >  Repository: pborreli/accessible-html5-video-player
   >  Repository: pborreli/Adaptive-Images
   >  Repository: pborreli/addict
   >  Repository: pborreli/adept-jpg-compressor
   >  Repository: pborreli/admin-bundle
   >  Repository: pborreli/aidkit
   >  Repository: pborreli/airstream
   >  Repository: pborreli/alice
   >  Repository: pborreli/Amend
   >  Repository: pborreli/Anemometer
   >  Repository: pborreli/angular.js
   >  Repository: pborreli/anijs
   >  Repository: pborreli/annotations
   >  Repository: pborreli/annotations-1
   >  Repository: pborreli/ansible
   >  Repository: pborreli/ansible-modules-core
   >  Repository: pborreli/api-standards
   >  Repository: pborreli/app
   >  Repository: pborreli/arcanist
   >  Repository: pborreli/arrow
   >  Repository: pborreli/ArtBreadcrumbsBundle
   >  Repository: pborreli/ArteHateoasBundle
   >  Repository: pborreli/assert
   >  Repository: pborreli/assetic
   >  Repository: pborreli/assez-tic-de-perdre-du-temps-automatisez-conf
   >  Repository: pborreli/At.js
   >  Repository: pborreli/athletic
   >  Repository: pborreli/atom
   >  Repository: pborreli/atom-lint
   >  Repository: pborreli/atom-shell
   >  Repository: pborreli/atomic-site
   >  Repository: pborreli/atoum
   >  Repository: pborreli/Aura.Di
   >  Repository: pborreli/Aura.Filter
   >  Repository: pborreli/Aura.Framework
   >  Repository: pborreli/Aura.Http
   >  Repository: pborreli/Aura.Intl
   >  Repository: pborreli/Aura.Marshal
   >  Repository: pborreli/Aura.Sql
   >  Repository: pborreli/Aura.View
   >  Repository: pborreli/Aura.Web
   >  Repository: pborreli/auraphp.github.com
   >  Repository: pborreli/AutoLogin
   >  Repository: pborreli/automating-workflow-ticonf2014-talk
   >  Repository: pborreli/awesome-symfony2
   >  Repository: pborreli/aws-sdk-php
   >  Repository: pborreli/AzureDistributionBundle
   >  Repository: pborreli/backbone-events-standalone
   >  Repository: pborreli/backup-manager
   >  Repository: pborreli/BadFaith
   >  Repository: pborreli/badge-poser
   >  Repository: pborreli/barcha.github.com
   >  Repository: pborreli/barometre
   >  Repository: pborreli/bashblog
   >  Repository: pborreli/BazingaFakerBundle
   >  Repository: pborreli/BazingaGeocoderBundle
   >  Repository: pborreli/Behat
   >  Repository: pborreli/behatch-contexts
   >  Repository: pborreli/BehatPageObjectExtension
   >  Repository: pborreli/behind-github-geojson
   >  Repository: pborreli/benbalter.github.com
   >  Repository: pborreli/bernard
   >  Repository: pborreli/BeSimpleSsoAuthBundle
   >  Repository: pborreli/best-bundle-conf
   >  Repository: pborreli/biscotto
   >  Repository: pborreli/blog
   >  Repository: pborreli/blog-1
   >  Repository: pborreli/blog-2
   >  Repository: pborreli/blog_liip_ch_posts
   >  Repository: pborreli/bodaclick.github.com
   >  Repository: pborreli/bolt
   >  Repository: pborreli/Book-of-Speed
   >  Repository: pborreli/boom
   >  Repository: pborreli/bootstrap
   >  Repository: pborreli/boris
   >  Repository: pborreli/bower
   >  Repository: pborreli/Box
   >  Repository: pborreli/breach_core
   >  Repository: pborreli/broker
   >  Repository: pborreli/browser-diet
   >  Repository: pborreli/buffer-blog-v2
   >  Repository: pborreli/buffer-bot
   >  Repository: pborreli/buffer-chrome
   >  Repository: pborreli/buffer-extension-shared
   >  Repository: pborreli/bufferbot-slack
   >  Repository: pborreli/burn
   >  Repository: pborreli/Buzz
   >  Repository: pborreli/bxslider-4
   >  Repository: pborreli/c4
   >  Repository: pborreli/ca-marche-chez-moi
   >  Repository: pborreli/cache
   >  Repository: pborreli/cache-1
   >  Repository: pborreli/cada
   >  Repository: pborreli/cadvisor
   >  Repository: pborreli/Cakebrew
   >  Repository: pborreli/cakephp
   >  Repository: pborreli/Carbon
   >  Repository: pborreli/carte
   >  Repository: pborreli/cartographer
   >  Repository: pborreli/casperjs
   >  Repository: pborreli/chad.github.io
   >  Repository: pborreli/chancejs
   >  Repository: pborreli/Chart.js
   >  Repository: pborreli/cheddar-mac
   >  Repository: pborreli/choosealicense.com
   >  Repository: pborreli/chute
   >  Repository: pborreli/ClassPreloader
   >  Repository: pborreli/climate
   >  Repository: pborreli/clockwork
   >  Repository: pborreli/cmf-sandbox
   >  Repository: pborreli/Codeception
   >  Repository: pborreli/coding-standard
   >  Repository: pborreli/colada
   >  Repository: pborreli/collections
   >  Repository: pborreli/CommentsBundle
   >  Repository: pborreli/common
   >  Repository: pborreli/Common-1
   >  Repository: pborreli/common-documentation
   >  Repository: pborreli/composer
   >  Repository: pborreli/composer-service
   >  Repository: pborreli/connect
   >  Repository: pborreli/ControllerUtil
   >  Repository: pborreli/CoopTilleulsCKEditorSonataMediaBundle
   >  Repository: pborreli/coreclr
   >  Repository: pborreli/crm
   >  Repository: pborreli/cron-expression
   >  Repository: pborreli/CrowdinBundle
   >  Repository: pborreli/csv
   >  Repository: pborreli/customelements.io
   >  Repository: pborreli/damnit
   >  Repository: pborreli/data-fixtures
   >  Repository: pborreli/database
   >  Repository: pborreli/datagov-design
   >  Repository: pborreli/datum
   >  Repository: pborreli/dbal
   >  Repository: pborreli/DeadDropDocs
   >  Repository: pborreli/deep_thought
   >  Repository: pborreli/DenetmenBundle
   >  Repository: pborreli/dev-human
   >  Repository: pborreli/devdocs
   >  Repository: pborreli/developer.github.com
   >  Repository: pborreli/dflydev-markdown
   >  Repository: pborreli/diggdigg
   >  Repository: pborreli/discussion
   >  Repository: pborreli/django-project-template
   >  Repository: pborreli/django-rest-framework
   >  Repository: pborreli/doc.php
   >  Repository: pborreli/docker
   >  Repository: pborreli/docker-php
   >  Repository: pborreli/docs
   >  Repository: pborreli/docs-1
   >  Repository: pborreli/docs-2
   >  Repository: pborreli/docs-3
   >  Repository: pborreli/docs-4
   >  Repository: pborreli/docs-5
   >  Repository: pborreli/docs.drone.io
   >  Repository: pborreli/doctrine-extra-bundle
   >  Repository: pborreli/doctrine2
   >  Repository: pborreli/DoctrineCacheBundle
   >  Repository: pborreli/DoctrineExtensions
   >  Repository: pborreli/DoctrineModule
   >  Repository: pborreli/DoctrineMongoDBBundle
   >  Repository: pborreli/DoctrinePHPCRBundle
   >  Repository: pborreli/documentation
   >  Repository: pborreli/documentation-1
   >  Repository: pborreli/documentation-2
   >  Repository: pborreli/documentation-3
   >  Repository: pborreli/dogpatch
   >  Repository: pborreli/dotnet
   >  Repository: pborreli/drest
   >  Repository: pborreli/drgomesp.github.com
   >  Repository: pborreli/dropzone
   >  Repository: pborreli/duo
   >  Repository: pborreli/EasyAdminBundle
   >  Repository: pborreli/ecommerce
   >  Repository: pborreli/editor
   >  Repository: pborreli/EkinoNewRelicBundle
   >  Repository: pborreli/ElaoFormTranslationBundle
   >  Repository: pborreli/elastica-conf
   >  Repository: pborreli/elasticsearch
   >  Repository: pborreli/elasticsearch-bundle
   >  Repository: pborreli/elasticsearch-php
   >  Repository: pborreli/elcaro
   >  Repository: pborreli/elcodi
   >  Repository: pborreli/elcodi-blog
   >  Repository: pborreli/elcodi-docs
   >  Repository: pborreli/elephant
   >  Repository: pborreli/email-test
   >  Repository: pborreli/EmailReplyParser
   >  Repository: pborreli/emailvision
   >  Repository: pborreli/en-docs.behat.org
   >  Repository: pborreli/en-mink.behat.org
   >  Repository: pborreli/end-to-end
   >  Repository: pborreli/endcredits
   >  Repository: pborreli/EntityAudit
   >  Repository: pborreli/envoy
   >  Repository: pborreli/exporter
   >  Repository: pborreli/ezforms-bundle
   >  Repository: pborreli/ezpublish-kernel
   >  Repository: pborreli/ezpublish-legacy
   >  Repository: pborreli/ezpublish-legacy-extension-installer
   >  Repository: pborreli/ezpublish-migrations-bundle
   >  Repository: pborreli/ezpublish5
   >  Repository: pborreli/ezpublish5-and-symfony2
   >  Repository: pborreli/eZPublishProxyConnect
   >  Repository: pborreli/f43.me
   >  Repository: pborreli/fail2ban
   >  Repository: pborreli/Faker
   >  Repository: pborreli/fatfree
   >  Repository: pborreli/feedback
   >  Repository: pborreli/FeedBundle
   >  Repository: pborreli/fenom
   >  Repository: pborreli/fig-standards
   >  Repository: pborreli/Finite
   >  Repository: pborreli/firing-range
   >  Repository: pborreli/fixthatcode.com
   >  Repository: pborreli/flickholdr
   >  Repository: pborreli/flight
   >  Repository: pborreli/flight-1
   >  Repository: pborreli/flow
   >  Repository: pborreli/flux
   >  Repository: pborreli/Flysystem
   >  Repository: pborreli/fnordmetric
   >  Repository: pborreli/forceutf8
   >  Repository: pborreli/forkcms
   >  Repository: pborreli/Form
   >  Repository: pborreli/fortyfour
   >  Repository: pborreli/FOSHttpCacheBundle
   >  Repository: pborreli/FOSMessageBundle
   >  Repository: pborreli/FOSRestBundle
   >  Repository: pborreli/FOSUserBundle
   >  Repository: pborreli/foundation
   >  Repository: pborreli/fractal
   >  Repository: pborreli/framework
   >  Repository: pborreli/framework-1
   >  Repository: pborreli/french-tech-hall-of-fame
   >  Repository: pborreli/Front-end-Developer-Interview-Questions
   >  Repository: pborreli/FullHackerNews
   >  Repository: pborreli/fzaninotto.github.com
   >  Repository: pborreli/gaspaio.github.com
   >  Repository: pborreli/gaudi
   >  Repository: pborreli/Gaufrette
   >  Repository: pborreli/geekweek12
   >  Repository: pborreli/generator-joli-symfony
   >  Repository: pborreli/genghis
   >  Repository: pborreli/GeocodableBehavior
   >  Repository: pborreli/Geocoder
   >  Repository: pborreli/geocoder-silex
   >  Repository: pborreli/geojson
   >  Repository: pborreli/geojson-diff
   >  Repository: pborreli/GeonamesServer
   >  Repository: pborreli/GeonamesServer-1
   >  Repository: pborreli/Geotools
   >  Repository: pborreli/gh-downloader
   >  Repository: pborreli/Ghost
   >  Repository: pborreli/git-internals-pdf
   >  Repository: pborreli/gitbook
   >  Repository: pborreli/github-todos
   >  Repository: pborreli/GithubTeamReviewer
   >  Repository: pborreli/githut
   >  Repository: pborreli/gitlist
   >  Repository: pborreli/gitonomy

Error: spawn EAGAIN
    at errnoException (child_process.js:1011:11)
    at ChildProcess.spawn (child_process.js:958:11)
    at exports.spawn (child_process.js:746:9)
    at Object.exports.execFile (child_process.js:628:15)
    at exports.exec (child_process.js:591:18)
    at Gry.exec (/Users/pborreli/Contrib/repository-downloader/node_modules/gry/lib/index.js:33:5)
    at /Users/pborreli/Contrib/repository-downloader/github.js:187:18
    at /Users/pborreli/Contrib/repository-downloader/node_modules/async/lib/async.js:570:21
    at /Users/pborreli/Contrib/repository-downloader/node_modules/async/lib/async.js:249:17
    at /Users/pborreli/Contrib/repository-downloader/node_modules/async/lib/async.js:125:13
info  Getting the organizations you belong to.

### PR DESCRIPTION
**Pull request by IonicaBizau**
- Improved the error handling. Fixes #3.
 - Upgraded to `gry@2.1.0` having process limit. Fixed #4 
 - Check if the `config.json` file exists.

### CODE REVIEW

**Comment by IonicaBizau** [comment]
@pborreli Can you please test the changes from this branch?

**Comment by pborreli** [comment]
still failing but after more time : 

```
➜  repository-downloader (check-pr-items) ✔ ./start
info  Getting the organizations you belong to.
info  Getting all your repositories.
   >  Page: 1
   >  Page: 2
   >  Page: 3
   >  Page: 4
   >  Page: 5
   >  Page: 6
   >  Page: 7
   >  Page: 8
   >  Page: 9
info  Getting the repositories where pborreli created pull requests.
   >  Page: 1
   >  Page: 2
   >  Page: 3
   >  Page: 4
   >  Page: 5
   >  Page: 6
   >  Page: 7
   >  Page: 8
   >  Page: 9
   >  Page: 10
   >  Page: 11
warn  Only the first 1000 search results are available
info  Downloading all your repositories.
   >  Repository: pborreli/18f.gsa.gov
   >  Repository: pborreli/24pullrequests
   >  Repository: pborreli/42-protips-2014-conf
warn  Repository already downloaded: pborreli/AB
   >  Repository: pborreli/accessible-html5-video-player
   >  Repository: pborreli/Adaptive-Images
   >  Repository: pborreli/addict
   >  Repository: pborreli/adept-jpg-compressor
   >  Repository: pborreli/admin-bundle
   >  Repository: pborreli/aidkit
warn  Repository already downloaded: pborreli/airstream
   >  Repository: pborreli/alice
warn  Repository already downloaded: pborreli/Amend
   >  Repository: pborreli/Anemometer
   >  Repository: pborreli/angular.js
warn  Repository already downloaded: pborreli/anijs
   >  Repository: pborreli/annotations
   >  Repository: pborreli/annotations-1
   >  Repository: pborreli/ansible
   >  Repository: pborreli/ansible-modules-core
   >  Repository: pborreli/api-standards
   >  Repository: pborreli/app
   >  Repository: pborreli/arcanist
   >  Repository: pborreli/arrow
   >  Repository: pborreli/ArtBreadcrumbsBundle
   >  Repository: pborreli/ArteHateoasBundle
warn  Repository already downloaded: pborreli/assert
   >  Repository: pborreli/assetic
   >  Repository: pborreli/assez-tic-de-perdre-du-temps-automatisez-conf
   >  Repository: pborreli/At.js
   >  Repository: pborreli/athletic
   >  Repository: pborreli/atom
   >  Repository: pborreli/atom-lint
   >  Repository: pborreli/atom-shell
   >  Repository: pborreli/atomic-site
   >  Repository: pborreli/atoum
   >  Repository: pborreli/Aura.Di
   >  Repository: pborreli/Aura.Filter
   >  Repository: pborreli/Aura.Framework
   >  Repository: pborreli/Aura.Http
   >  Repository: pborreli/Aura.Intl
   >  Repository: pborreli/Aura.Marshal
   >  Repository: pborreli/Aura.Sql
   >  Repository: pborreli/Aura.View
   >  Repository: pborreli/Aura.Web
   >  Repository: pborreli/auraphp.github.com
   >  Repository: pborreli/AutoLogin
   >  Repository: pborreli/automating-workflow-ticonf2014-talk
   >  Repository: pborreli/awesome-symfony2
   >  Repository: pborreli/aws-sdk-php
   >  Repository: pborreli/AzureDistributionBundle
warn  Repository already downloaded: pborreli/backbone-events-standalone
   >  Repository: pborreli/backup-manager
   >  Repository: pborreli/BadFaith
   >  Repository: pborreli/badge-poser
   >  Repository: pborreli/barcha.github.com
warn  Repository already downloaded: pborreli/barometre
   >  Repository: pborreli/bashblog
   >  Repository: pborreli/BazingaFakerBundle
   >  Repository: pborreli/BazingaGeocoderBundle
   >  Repository: pborreli/Behat
   >  Repository: pborreli/behatch-contexts
   >  Repository: pborreli/BehatPageObjectExtension
   >  Repository: pborreli/behind-github-geojson
   >  Repository: pborreli/benbalter.github.com
   >  Repository: pborreli/bernard
   >  Repository: pborreli/BeSimpleSsoAuthBundle
   >  Repository: pborreli/best-bundle-conf
   >  Repository: pborreli/biscotto
   >  Repository: pborreli/blog
   >  Repository: pborreli/blog-1
   >  Repository: pborreli/blog-2
   >  Repository: pborreli/blog_liip_ch_posts
warn  Repository already downloaded: pborreli/bodaclick.github.com
   >  Repository: pborreli/bolt
   >  Repository: pborreli/Book-of-Speed
   >  Repository: pborreli/boom
   >  Repository: pborreli/bootstrap
   >  Repository: pborreli/boris
   >  Repository: pborreli/bower
   >  Repository: pborreli/Box
   >  Repository: pborreli/breach_core
warn  Repository already downloaded: pborreli/broker
   >  Repository: pborreli/browser-diet
   >  Repository: pborreli/buffer-blog-v2
   >  Repository: pborreli/buffer-bot
   >  Repository: pborreli/buffer-chrome
   >  Repository: pborreli/buffer-extension-shared
   >  Repository: pborreli/bufferbot-slack
   >  Repository: pborreli/burn
   >  Repository: pborreli/Buzz
   >  Repository: pborreli/bxslider-4
warn  Repository already downloaded: pborreli/c4
   >  Repository: pborreli/ca-marche-chez-moi
   >  Repository: pborreli/cache
   >  Repository: pborreli/cache-1
   >  Repository: pborreli/cada
   >  Repository: pborreli/cadvisor
   >  Repository: pborreli/Cakebrew
   >  Repository: pborreli/cakephp
   >  Repository: pborreli/Carbon
   >  Repository: pborreli/carte
warn  Repository already downloaded: pborreli/cartographer
   >  Repository: pborreli/casperjs
   >  Repository: pborreli/chad.github.io
   >  Repository: pborreli/chancejs
   >  Repository: pborreli/Chart.js
   >  Repository: pborreli/cheddar-mac
   >  Repository: pborreli/choosealicense.com
   >  Repository: pborreli/chute
   >  Repository: pborreli/ClassPreloader
   >  Repository: pborreli/climate
   >  Repository: pborreli/clockwork
   >  Repository: pborreli/cmf-sandbox
   >  Repository: pborreli/Codeception
warn  Repository already downloaded: pborreli/coding-standard
   >  Repository: pborreli/colada
   >  Repository: pborreli/collections
   >  Repository: pborreli/CommentsBundle
   >  Repository: pborreli/common
   >  Repository: pborreli/Common-1
warn  Repository already downloaded: pborreli/common-documentation
   >  Repository: pborreli/composer
   >  Repository: pborreli/composer-service
   >  Repository: pborreli/connect
   >  Repository: pborreli/ControllerUtil
   >  Repository: pborreli/CoopTilleulsCKEditorSonataMediaBundle
   >  Repository: pborreli/coreclr
   >  Repository: pborreli/crm
   >  Repository: pborreli/cron-expression
   >  Repository: pborreli/CrowdinBundle
   >  Repository: pborreli/csv
   >  Repository: pborreli/customelements.io
   >  Repository: pborreli/damnit
   >  Repository: pborreli/data-fixtures
   >  Repository: pborreli/database
   >  Repository: pborreli/datagov-design
   >  Repository: pborreli/datum
   >  Repository: pborreli/dbal
   >  Repository: pborreli/DeadDropDocs
   >  Repository: pborreli/deep_thought
   >  Repository: pborreli/DenetmenBundle
   >  Repository: pborreli/dev-human
   >  Repository: pborreli/devdocs
   >  Repository: pborreli/developer.github.com
warn  Repository already downloaded: pborreli/dflydev-markdown
   >  Repository: pborreli/diggdigg
   >  Repository: pborreli/discussion
   >  Repository: pborreli/django-project-template
   >  Repository: pborreli/django-rest-framework
   >  Repository: pborreli/doc.php
   >  Repository: pborreli/docker
   >  Repository: pborreli/docker-php
   >  Repository: pborreli/docs
   >  Repository: pborreli/docs-1
   >  Repository: pborreli/docs-2
   >  Repository: pborreli/docs-3
   >  Repository: pborreli/docs-4
   >  Repository: pborreli/docs-5
   >  Repository: pborreli/docs.drone.io
   >  Repository: pborreli/doctrine-extra-bundle
   >  Repository: pborreli/doctrine2
   >  Repository: pborreli/DoctrineCacheBundle
   >  Repository: pborreli/DoctrineExtensions
   >  Repository: pborreli/DoctrineModule
   >  Repository: pborreli/DoctrineMongoDBBundle
   >  Repository: pborreli/DoctrinePHPCRBundle
warn  Repository already downloaded: pborreli/documentation
   >  Repository: pborreli/documentation-1
   >  Repository: pborreli/documentation-2
   >  Repository: pborreli/documentation-3
   >  Repository: pborreli/dogpatch
   >  Repository: pborreli/dotnet
   >  Repository: pborreli/drest
   >  Repository: pborreli/drgomesp.github.com
   >  Repository: pborreli/dropzone
   >  Repository: pborreli/duo
   >  Repository: pborreli/EasyAdminBundle
   >  Repository: pborreli/ecommerce
   >  Repository: pborreli/editor
   >  Repository: pborreli/EkinoNewRelicBundle
   >  Repository: pborreli/ElaoFormTranslationBundle
   >  Repository: pborreli/elastica-conf
   >  Repository: pborreli/elasticsearch
   >  Repository: pborreli/elasticsearch-bundle
   >  Repository: pborreli/elasticsearch-php
   >  Repository: pborreli/elcaro
   >  Repository: pborreli/elcodi
   >  Repository: pborreli/elcodi-blog
warn  Repository already downloaded: pborreli/elcodi-docs
   >  Repository: pborreli/elephant
warn  Repository already downloaded: pborreli/email-test
   >  Repository: pborreli/EmailReplyParser
   >  Repository: pborreli/emailvision
   >  Repository: pborreli/en-docs.behat.org
   >  Repository: pborreli/en-mink.behat.org
   >  Repository: pborreli/end-to-end
   >  Repository: pborreli/endcredits
   >  Repository: pborreli/EntityAudit
   >  Repository: pborreli/envoy
   >  Repository: pborreli/exporter
   >  Repository: pborreli/ezforms-bundle
   >  Repository: pborreli/ezpublish-kernel
   >  Repository: pborreli/ezpublish-legacy
   >  Repository: pborreli/ezpublish-legacy-extension-installer
   >  Repository: pborreli/ezpublish-migrations-bundle
   >  Repository: pborreli/ezpublish5
   >  Repository: pborreli/ezpublish5-and-symfony2
   >  Repository: pborreli/eZPublishProxyConnect
   >  Repository: pborreli/f43.me
   >  Repository: pborreli/fail2ban
   >  Repository: pborreli/Faker
   >  Repository: pborreli/fatfree
   >  Repository: pborreli/feedback
   >  Repository: pborreli/FeedBundle
   >  Repository: pborreli/fenom
   >  Repository: pborreli/fig-standards
   >  Repository: pborreli/Finite
   >  Repository: pborreli/firing-range
   >  Repository: pborreli/fixthatcode.com
   >  Repository: pborreli/flickholdr
   >  Repository: pborreli/flight
   >  Repository: pborreli/flight-1
   >  Repository: pborreli/flow
warn  Repository already downloaded: pborreli/flux
   >  Repository: pborreli/Flysystem
   >  Repository: pborreli/fnordmetric
   >  Repository: pborreli/forceutf8
   >  Repository: pborreli/forkcms
   >  Repository: pborreli/Form
   >  Repository: pborreli/fortyfour
   >  Repository: pborreli/FOSHttpCacheBundle
   >  Repository: pborreli/FOSMessageBundle
   >  Repository: pborreli/FOSRestBundle
   >  Repository: pborreli/FOSUserBundle
   >  Repository: pborreli/foundation
   >  Repository: pborreli/fractal
   >  Repository: pborreli/framework
   >  Repository: pborreli/framework-1
warn  Repository already downloaded: pborreli/french-tech-hall-of-fame
   >  Repository: pborreli/Front-end-Developer-Interview-Questions
   >  Repository: pborreli/FullHackerNews
   >  Repository: pborreli/fzaninotto.github.com
   >  Repository: pborreli/gaspaio.github.com
   >  Repository: pborreli/gaudi
   >  Repository: pborreli/Gaufrette
   >  Repository: pborreli/geekweek12
   >  Repository: pborreli/generator-joli-symfony
   >  Repository: pborreli/genghis
   >  Repository: pborreli/GeocodableBehavior
   >  Repository: pborreli/Geocoder
   >  Repository: pborreli/geocoder-silex
   >  Repository: pborreli/geojson
   >  Repository: pborreli/geojson-diff
   >  Repository: pborreli/GeonamesServer
   >  Repository: pborreli/GeonamesServer-1
   >  Repository: pborreli/Geotools
   >  Repository: pborreli/gh-downloader
   >  Repository: pborreli/Ghost
   >  Repository: pborreli/git-internals-pdf
   >  Repository: pborreli/gitbook
   >  Repository: pborreli/github-todos
   >  Repository: pborreli/GithubTeamReviewer
   >  Repository: pborreli/githut
   >  Repository: pborreli/gitlist
   >  Repository: pborreli/gitonomy
   >  Repository: pborreli/gitscm-next
   >  Repository: pborreli/gman
   >  Repository: pborreli/go-socket.io
   >  Repository: pborreli/godropbox
   >  Repository: pborreli/google-analytics
   >  Repository: pborreli/google-map

Error: spawn EAGAIN
    at errnoException (child_process.js:1011:11)
    at ChildProcess.spawn (child_process.js:958:11)
    at exports.spawn (child_process.js:746:9)
    at Object.exports.execFile (child_process.js:628:15)
    at exports.exec (child_process.js:591:18)
    at Gry.exec (/Users/pborreli/Contrib/repository-downloader/node_modules/gry/lib/index.js:33:5)
    at /Users/pborreli/Contrib/repository-downloader/github.js:187:18
    at /Users/pborreli/Contrib/repository-downloader/node_modules/async/lib/async.js:570:21
    at /Users/pborreli/Contrib/repository-downloader/node_modules/async/lib/async.js:249:17
    at /Users/pborreli/Contrib/repository-downloader/node_modules/async/lib/async.js:125:13

**Comment by pborreli** [comment]
ow wait forgot to launch `npm install`

**Comment by pborreli** [comment]
hmm same error : 

```
Error: spawn EAGAIN
    at errnoException (child_process.js:1011:11)
    at ChildProcess.spawn (child_process.js:958:11)
    at exports.spawn (child_process.js:746:9)
    at Object.exports.execFile (child_process.js:628:15)
    at LimitIt.exports.exec (child_process.js:591:18)
    at LimitIt.run (/Users/pborreli/Contrib/repository-downloader/node_modules/gry/node_modules/exec-limiter/node_modules/limit-it/lib/index.js:135:9)
    at LimitIt.check (/Users/pborreli/Contrib/repository-downloader/node_modules/gry/node_modules/exec-limiter/node_modules/limit-it/lib/index.js:106:14)
    at LimitIt.add (/Users/pborreli/Contrib/repository-downloader/node_modules/gry/node_modules/exec-limiter/node_modules/limit-it/lib/index.js:68:17)
    at ExecLimiter.add (/Users/pborreli/Contrib/repository-downloader/node_modules/gry/node_modules/exec-limiter/lib/index.js:40:18)
    at Gry.exec (/Users/pborreli/Contrib/repository-downloader/node_modules/gryinfo  Getting the organizations you belong to.

**Comment by IonicaBizau** [comment]
Please make sure you have `gry@2.0.1` (remove `node_modules` and do `npm install`).

**Comment by pborreli** [comment]
Same error 
```
➜  repository-downloader (check-pr-items) ✔ rm -rf node_modules
➜  repository-downloader (check-pr-items) ✔ npm install
async@0.9.0 node_modules/async

bug-killer@1.0.0 node_modules/bug-killer
└── couleurs@1.1.0 (x256@0.0.2)

gry@2.0.1 node_modules/gry
├── ul@1.1.0
└── exec-limiter@1.0.0 (limit-it@1.1.0)

request@2.53.0 node_modules/request
├── caseless@0.9.0
├── json-stringify-safe@5.0.0
├── forever-agent@0.5.2
├── aws-sign2@0.5.0
├── form-data@0.2.0
├── stringstream@0.0.4
├── oauth-sign@0.6.0
├── tunnel-agent@0.4.0
├── isstream@0.1.1
├── node-uuid@1.4.2
├── qs@2.3.3
├── combined-stream@0.0.7 (delayed-stream@0.0.5)
├── mime-types@2.0.9 (mime-db@1.7.0)
├── tough-cookie@0.12.1 (punycode@1.3.2)
├── http-signature@0.10.1 (assert-plus@0.1.5, asn1@0.1.11, ctype@0.5.3)
├── bl@0.9.4 (readable-stream@1.0.33)
└── hawk@2.3.1 (cryptiles@2.0.4, sntp@1.0.9, boom@2.6.1, hoek@2.11.0)

**Comment by IonicaBizau** [comment]
Share please the output of `ulimit -u`.

**Comment by pborreli** [comment]
ulimit -u
709

**Comment by pborreli** [comment]
btw why are you downloading repository who are forks ? I mean most of those repo have been created while i was doing PRs so it looks redundant with `Getting the repositories where pborreli created pull requests.`

**Comment by IonicaBizau** [comment]
The ulimit is pretty low I guess... But I will try to make the tool compatible with such a low `ulimit`. My output is:

```sh
$ ulimit -u
63640
 ```

In the meantime, please remove all the downloads (`rm -rf ./downloads/bitbucket ./downloads/github`), run the tool (`./start`) and when the repositories are being cloned do `ps aux | grep 'git clone' | wc -l` multiple times. Would be great to know what's the number returned just before crashing... I suppose it's lower than `30`.

> I mean most of those repo have been created while i was doing PRs
That's the idea, I try to get as many repositories where you contributed on GitHub. :smile:

**Comment by pborreli** [comment]
used : watch -n 1 "ps aux | grep 'git clone' | wc -l"

when it crashes it's 241

**Comment by IonicaBizau** [comment]
@pborreli Oh, I see. What do you think about https://github.com/IonicaBizau/node-gry/issues/3? Should I implement it or would it be better to change the code to create one `Gry` instance?

**Comment by pborreli** [comment]
I really don't know what could be the best implementation tbh

**Comment by IonicaBizau** [comment]
@pborreli Check if this is fixed via my latest commit in this branch (remove `node_modules` and do `npm install`).

I opened this PR: https://github.com/IonicaBizau/node-gry/pull/4

**Comment by pborreli** [comment]
it works :) now I have another issue later in the start process, and I know you already hate me lol

**Comment by IonicaBizau** [comment]
@pborreli Cool! Don't worry I love everybody that reports issues because we can fix them and make our tools even better. :smile:

**Pull request merged**
