### PR TITLE
Change Config.github to Config.bitbucket

### PR DESCRIPTION
**Pull request by longears**
fixes IonicaBizau/repository-downloader#6

### CODE REVIEW

**Comment by IonicaBizau** [comment]
Thanks! Looks good!  :+1: 

However, what's the difference between https://github.com/longears/repository-downloader/commit/f7ee9b61a3c2f4f1bfd6093dd53fac9b570a6ff6 and https://github.com/longears/repository-downloader/commit/60429ea8fa96f8b7c04c0f31cef018ceec3a90a9 ?

Could you tell me what commands did you run to reset the first commit?

**Comment by IonicaBizau** [comment]
Ah, got it. You created a pull request into your fork. :smile:

**Comment by longears** [comment]
Yep.  Accidentally created a pull request into my own fork.  :)  Deleted my fork and did it again the right way.

**Comment by IonicaBizau** [comment]
Thanks! :+1:

**Pull request merged**
